# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from abc import abstractmethod, ABC

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, Qt, QMimeData, QPoint, QEvent, QItemSelectionModel
from PyQt5.QtGui import QPixmap, QDrag, QCursor, QRegion, QColor
from PyQt5.QtWidgets import QWidget, QLineEdit, QInputDialog, QMainWindow, QTreeWidgetItem, QListView
from matplotlib.markers import MarkerStyle

from Console_Objets.Figure import Figure
from Resources_file import Resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_left = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayout_left.setMaximumSize(QtCore.QSize(427, 16777215))
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayout_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = Tree_widget(self.verticalLayout_left)
        self.treeWidget.setMinimumSize(QtCore.QSize(405, 217))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 278))
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Name")
        self.verticalLayout.addWidget(self.treeWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayout_left)
        self.label.setMinimumSize(QtCore.QSize(0, 18))
        self.label.setMaximumSize(QtCore.QSize(651, 18))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.verticalLayout_left)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalLayout_left)
        self.label_7.setMinimumSize(QtCore.QSize(127, 41))
        self.label_7.setMaximumSize(QtCore.QSize(127, 41))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayout_left)
        self.comboBox_5.setMinimumSize(QtCore.QSize(103, 41))
        self.comboBox_5.setMaximumSize(QtCore.QSize(103, 41))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayout_left)
        self.pushButton_5.setMinimumSize(QtCore.QSize(103, 41))
        self.pushButton_5.setMaximumSize(QtCore.QSize(103, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayout_left)
        self.label_5.setMinimumSize(QtCore.QSize(0, 18))
        self.label_5.setMaximumSize(QtCore.QSize(651, 18))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.line_2 = QtWidgets.QFrame(self.verticalLayout_left)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayout_left)
        self.label_6.setMinimumSize(QtCore.QSize(127, 41))
        self.label_6.setMaximumSize(QtCore.QSize(127, 41))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayout_left)
        self.comboBox_4.setMinimumSize(QtCore.QSize(103, 41))
        self.comboBox_4.setMaximumSize(QtCore.QSize(103, 41))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayout_left)
        self.pushButton_4.setMinimumSize(QtCore.QSize(103, 41))
        self.pushButton_4.setMaximumSize(QtCore.QSize(103, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.listWidget = QtWidgets.QListWidget(self.verticalLayout_left)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout.addWidget(self.listWidget)

        self.horizontalLayout.addWidget(self.verticalLayout_left)
        self.tabWidget = TabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 26))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menumodulo = QtWidgets.QMenu(self.menuOpen)
        self.menumodulo.setObjectName("menumodulo")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncccv = QtWidgets.QAction(MainWindow)
        self.actioncccv.setObjectName("actioncccv")
        self.actioncv = QtWidgets.QAction(MainWindow)
        self.actioncv.setObjectName("actioncv")
        self.actiongitt = QtWidgets.QAction(MainWindow)
        self.actiongitt.setObjectName("actiongitt")
        self.actioncp = QtWidgets.QAction(MainWindow)
        self.actioncp.setObjectName("actioncp")
        self.actiondiffracion = QtWidgets.QAction(MainWindow)
        self.actiondiffracion.setObjectName("actiondiffracion")
        self.actionIhch_1501 = QtWidgets.QAction(MainWindow)
        self.actionIhch_1501.setObjectName("actionIhch_1501")
        self.actionvieillissement = QtWidgets.QAction(MainWindow)
        self.actionvieillissement.setObjectName("actionvieillissement")
        self.actionEdit_Current_Plot = QtWidgets.QAction(MainWindow)
        self.actionEdit_Current_Plot.setObjectName("actionEdit_Current_Plot")
        self.actionDelete_Current_Plot = QtWidgets.QAction(MainWindow)
        self.actionDelete_Current_Plot.setObjectName("actionDelete_Current_Plot")
        self.actionPlot = QtWidgets.QAction(MainWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actionR_sistance = QtWidgets.QAction(MainWindow)
        self.actionR_sistance.setObjectName("actionR_sistance")
        self.actionArea = QtWidgets.QAction(MainWindow)
        self.actionArea.setObjectName("actionArea")
        self.actionDiffraction = QtWidgets.QAction(MainWindow)
        self.actionDiffraction.setObjectName("actionDiffraction")
        self.actionCurrent_Plot = QtWidgets.QAction(MainWindow)
        self.actionCurrent_Plot.setObjectName("actionCurrent_Plot")
        self.actionCurrend_Data = QtWidgets.QAction(MainWindow)
        self.actionCurrend_Data.setObjectName("actionCurrend_Data")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.menumodulo.addAction(self.actionvieillissement)
        self.menuOpen.addAction(self.actioncccv)
        self.menuOpen.addAction(self.actioncv)
        self.menuOpen.addAction(self.actiongitt)
        self.menuOpen.addAction(self.actioncp)
        self.menuOpen.addAction(self.actiondiffracion)
        self.menuOpen.addAction(self.actionIhch_1501)
        self.menuOpen.addAction(self.menumodulo.menuAction())
        self.menuPlot.addAction(self.actionEdit_Current_Plot)
        self.menuPlot.addAction(self.actionDelete_Current_Plot)
        self.menuExport.addAction(self.actionPlot)
        self.menuExport.addAction(self.actionR_sistance)
        self.menuExport.addAction(self.actionArea)
        self.menuExport.addAction(self.actionDiffraction)
        self.menuSave.addAction(self.actionCurrent_Plot)
        self.menuSave.addAction(self.actionCurrend_Data)
        self.menuSave.addAction(self.actionAll)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.listWidget.setStyleSheet("""QListWidget{background: black;}
                                        QListWidget::item:disabled{background: transparent;}""")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:11pt;\">Current data : None</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">New plot</span></p></body></html>"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "capa"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "potetio"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "custom"))
        self.pushButton_5.setText(_translate("MainWindow", "Create"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:11pt;\">Current plot : None</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Action</span></p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Derive"))
        self.pushButton_4.setText(_translate("MainWindow", "Create"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menumodulo.setTitle(_translate("MainWindow", "modulo"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.actioncccv.setText(_translate("MainWindow", "cccv"))
        self.actioncv.setText(_translate("MainWindow", "cv"))
        self.actiongitt.setText(_translate("MainWindow", "gitt"))
        self.actioncp.setText(_translate("MainWindow", "cp"))
        self.actiondiffracion.setText(_translate("MainWindow", "diffraction"))
        self.actionIhch_1501.setText(_translate("MainWindow", "Ihch 1501"))
        self.actionvieillissement.setText(_translate("MainWindow", "vieillissement"))
        self.actionEdit_Current_Plot.setText(_translate("MainWindow", "Edit Current Plot"))
        self.actionDelete_Current_Plot.setText(_translate("MainWindow", "Delete Current Plot"))
        self.actionPlot.setText(_translate("MainWindow", "Plot"))
        self.actionR_sistance.setText(_translate("MainWindow", "Résistance"))
        self.actionArea.setText(_translate("MainWindow", "Area"))
        self.actionDiffraction.setText(_translate("MainWindow", "Diffraction"))
        self.actionCurrent_Plot.setText(_translate("MainWindow", "Current Plot"))
        self.actionCurrend_Data.setText(_translate("MainWindow", "Currend Data"))
        self.actionAll.setText(_translate("MainWindow", "All"))



class UI_Create_Figure(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 434)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(111, 41))
        self.label_13.setMaximumSize(QtCore.QSize(111, 41))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(111, 41))
        self.lineEdit.setMaximumSize(QtCore.QSize(111, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_3.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_15.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_15.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_15)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(111, 41))
        self.pushButton_10.setMaximumSize(QtCore.QSize(111, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_6.addWidget(self.pushButton_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.listView_3 = QtWidgets.QListView(self.tab_2)
        self.listView_3.setMaximumSize(QtCore.QSize(136, 137))
        self.listView_3.setObjectName("listView_3")
        self.horizontalLayout_9.addWidget(self.listView_3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setMinimumSize(QtCore.QSize(111, 41))
        self.label_14.setMaximumSize(QtCore.QSize(111, 41))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.comboBox_16 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_16.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_16.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_16)
        self.gridLayout_5.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        self.label_15.setMinimumSize(QtCore.QSize(111, 41))
        self.label_15.setMaximumSize(QtCore.QSize(111, 41))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.comboBox_17 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_17.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_17.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_17)
        self.gridLayout_5.addWidget(self.frame_6, 1, 0, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_16)
        self.tabWidget_3.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_12 = QtWidgets.QComboBox(self.tab)
        self.comboBox_12.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_12.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setMinimumSize(QtCore.QSize(111, 41))
        self.pushButton_9.setMaximumSize(QtCore.QSize(111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(50, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.listView_2 = QtWidgets.QListView(self.tab)
        self.listView_2.setMinimumSize(QtCore.QSize(136, 137))
        self.listView_2.setMaximumSize(QtCore.QSize(136, 137))
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout_4.addWidget(self.listView_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setMinimumSize(QtCore.QSize(111, 41))
        self.label_11.setMaximumSize(QtCore.QSize(111, 41))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_13.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_13.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_13)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setMinimumSize(QtCore.QSize(111, 41))
        self.label_12.setMaximumSize(QtCore.QSize(111, 41))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_14.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_14.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_14)
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_14)
        self.tabWidget_3.addTab(self.tab, "")
        self.RightAxe = QtWidgets.QWidget()
        self.RightAxe.setObjectName("RightAxe")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.RightAxe)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_18 = QtWidgets.QComboBox(self.RightAxe)
        self.comboBox_18.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_18.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_18)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.pushButton_11 = QtWidgets.QPushButton(self.RightAxe)
        self.pushButton_11.setMinimumSize(QtCore.QSize(111, 41))
        self.pushButton_11.setMaximumSize(QtCore.QSize(111, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_7.addWidget(self.pushButton_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(50, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.listView_4 = QtWidgets.QListView(self.RightAxe)
        self.listView_4.setMinimumSize(QtCore.QSize(136, 137))
        self.listView_4.setMaximumSize(QtCore.QSize(136, 137))
        self.listView_4.setObjectName("listView_4")
        self.horizontalLayout_7.addWidget(self.listView_4)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.RightAxe)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setMinimumSize(QtCore.QSize(111, 41))
        self.label_16.setMaximumSize(QtCore.QSize(111, 41))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.comboBox_19 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_19.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_19.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_19)
        self.gridLayout_6.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.RightAxe)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        self.label_17.setMinimumSize(QtCore.QSize(111, 41))
        self.label_17.setMaximumSize(QtCore.QSize(111, 41))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.comboBox_20 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_20.setMinimumSize(QtCore.QSize(111, 41))
        self.comboBox_20.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_20)
        self.gridLayout_6.addWidget(self.frame_8, 1, 0, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_15)
        self.tabWidget_3.addTab(self.RightAxe, "")
        self.verticalLayout.addWidget(self.tabWidget_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create new Figure"))
        self.label_13.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Name</span></p></body></html>"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "time/h"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Ecell/V"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "<i>/mA"))
        self.pushButton_10.setText(_translate("MainWindow", "Add data"))
        self.label_14.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Unite</span></p></body></html>"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "linear"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "log"))
        self.label_15.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Scale</span></p></body></html>"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "test1"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "test2"))
        self.comboBox_17.setItemText(2, _translate("MainWindow", "test3"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("MainWindow", "X Axe"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "time/h"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "Ecell/V"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "<i>/mA"))
        self.pushButton_9.setText(_translate("MainWindow", "Add data"))
        self.label_11.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Unite</span></p></body></html>"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "linear"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "log"))
        self.label_12.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Scale</span></p></body></html>"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "test1"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "test2"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "test3"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "Left Axe"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "time/h"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "Ecell/V"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "<i>/mA"))
        self.pushButton_11.setText(_translate("MainWindow", "Add data"))
        self.label_16.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Unite</span></p></body></html>"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "linear"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "log"))
        self.label_17.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Scale</span></p></body></html>"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "test1"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "test2"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "test3"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.RightAxe), _translate("MainWindow", "RightAxe"))
        self.pushButton.setText(_translate("MainWindow", "Create"))


class Tab(QWidget):
    drag_tab = pyqtSignal(int)

    def __init__(self):
        QWidget.__init__(self)


class TabWidget(QtWidgets.QTabWidget):
    name_changed_tab = pyqtSignal(str)
    break_tab = pyqtSignal(int)
    change_current = pyqtSignal(int)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setAcceptDrops(True)
        self.tabBar = self.tabBar()
        self.tabBar.setMouseTracking(True)
        self.setMovable(True)
        self.setAcceptDrops(True)

        self.tabBarDoubleClicked.connect(self.db_clique_bar)
        self.currentChanged.connect(self.onChange)
        self.tabBar.installEventFilter(self)

        self.start_drag_y = None

    def eventFilter(self, obj, event):
        if event.type() == QEvent.HoverMove:  # Catch the TouchBegin event.
            self.hoverMove(event)

        if event.type() == QEvent.MouseButtonPress:  # Catch the TouchBegin event.
            self.mousePressEvent(event)

        if event.type() == QEvent.MouseButtonRelease:  # Catch the TouchBegin event.
            self.mouseReleaseEvent(event)

        return super(TabWidget, self).eventFilter(obj, event)

    def db_clique_bar(self, event):
        name = QInputDialog.getText(self, "Name change", "New name ?", QLineEdit.Normal)
        if name[1] and name[0] != '':
            old_name = self.tabText(self.currentIndex())
            names = []
            for i in range(0, self.count()):
                if i != self.currentIndex():
                    names.append(self.tabText(i))

            new_name = Resources.unique_name(names, name[0])
            self.setTabText(self.currentIndex(), new_name)
            self.name_changed_tab.emit(old_name)

    def mousePressEvent(self, event):
        self.start_drag_y = event.y()

    def mouseReleaseEvent(self, event):
        self.start_drag_y = None

    def hoverMove(self, event):
        if self.start_drag_y is None:
            return
        sub = event.pos().y() - self.start_drag_y
        if sub > 50:
            self.break_tab.emit(self.currentIndex())
            self.removeTab(self.currentIndex())
            self.start_drag_y = None

    def onChange(self, event):
        self.change_current.emit(event)


class Edit_Axe(QWidget):
    finish = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(289, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 19))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(Dialog)
        self.comboBox_18.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.gridLayout.addWidget(self.comboBox_18, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(Dialog)
        self.comboBox_19.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout.addWidget(self.comboBox_19, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(75, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19, 0, QtCore.Qt.AlignLeft)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(75, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton.clicked.connect(self.save_presed)
        self.pushButton_2.clicked.connect(self.save_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p><span style=\" font-size:12pt;\">Edit Axe :</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:12pt;\">New name</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:12pt;\">Scale</span></p></body></html>"))
        self.comboBox_18.setItemText(0, _translate("Dialog", "Linear"))
        self.comboBox_18.setItemText(1, _translate("Dialog", "log"))
        self.label_17.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:12pt;\">Unite</span></p></body></html>"))
        self.comboBox_19.setItemText(0, _translate("Dialog", "test1"))
        self.comboBox_19.setItemText(1, _translate("Dialog", "test2"))
        self.comboBox_19.setItemText(2, _translate("Dialog", "test3"))
        self.label_18.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:12pt;\">Start at :</span></p></body></html>"))
        self.label_19.setText(_translate("Dialog",
                                         "<html><head/><body><p><span style=\" font-size:12pt;\">to :</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "save"))
        self.pushButton_2.setText(_translate("Dialog", "cancel"))

    def closeEvent(self, event):
        self.finish.emit("closed")

    def save_presed(self):
        self.finish.emit("save")

    def save_cancel(self):
        self.finish.emit("cancel")


class Edit_plot(QWidget):
    finish_signal = pyqtSignal(str)

    edit_signal = pyqtSignal(int)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Edit Plot")
        Dialog.resize(325, 313)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_left = QtWidgets.QComboBox(Dialog)
        self.comboBox_left.setObjectName("comboBox_left")
        self.gridLayout_2.addWidget(self.comboBox_left, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)


        self.comboBox_type_line_left = QtWidgets.QComboBox(Dialog)
        self.comboBox_type_line_left.setObjectName("comboBox_type_line_left")
        self.gridLayout_2.addWidget(self.comboBox_type_line_left, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)


        """self.comboBox_right = QtWidgets.QComboBox(Dialog)
        self.comboBox_right.setObjectName("comboBox_right")
        self.gridLayout_2.addWidget(self.comboBox_right, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)"""





        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton_3.clicked.connect(self.save)
        self.pushButton_5.clicked.connect(self.cancel)
        self.pushButton.clicked.connect(self.edit)
        self.pushButton_2.clicked.connect(self.hide)

        self.listWidget.currentItemChanged.connect(self.change_current)

        # vecteur qui garde la trace de quel axe a été édité
        self.edited = []

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Plot"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p><span style=\" font-size:18pt;\">Plot1</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Edit"))
        self.pushButton_2.setText(_translate("Dialog", "Hide"))
        self.label_5.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">Rescale Margin (%)</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">Color left axis</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">Style lines left axis</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "Save"))
        self.pushButton_5.setText(_translate("Dialog", "Cancel"))

        self.create_combobox_marker(self.comboBox_type_line_left)


    def save(self):
        self.finish_signal.emit("save")

    def cancel(self):
        self.finish_signal.emit("cancel")

    def closeEvent(self, event):
        self.finish_signal.emit("cancel")

    def change_current(self):
        if self.listWidget.currentItem() is not None:
            if self.listWidget.currentItem().foreground().color() == QColor("red") and self.pushButton_2.text() == "Hide":
                self.pushButton_2.setText("Show")
            elif self.listWidget.currentItem().foreground().color() == QColor("black") and self.pushButton_2.text() == "Show":
                self.pushButton_2.setText("Hide")

    def edit(self):
        self.edit_signal.emit(self.listWidget.currentRow())
        self.listWidget.item(0).foreground()

    def create_combobox_marker(self, combo_item):
        marker = MarkerStyle("o")
        print(marker.get_path())


    def hide(self):
        red = QColor("red")
        if self.listWidget.currentItem().foreground().color() == red:
            self.listWidget.currentItem().setForeground(QColor("black"))
            self.pushButton_2.setText("Hide")

        else:
            self.listWidget.currentItem().setForeground(red)
            self.pushButton_2.setText("Show")


class Tree_widget(QtWidgets.QTreeWidget):
    """
    on override QTreeWidget pour y ajouter des methode servant à
    l'ajout de figures et fichiers. Cette class représente l'arbre
    "pysique", c'est l'objet qui gére l'affichage, len events etc

    En plus de cette arbre, un arbre "logique" est créée, il comportera
    la même structure que l'arbre phyqiue dont il dépends. Il servira a
    faciliter les calcules pour l'insersion de nouvelles figures.
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.items = []

    """---------------------------------------------------------------------------------"""

    def add_data(self, type, name):
        """
        On ajoute la nouvelle data au tree

        :param type: type exp (cccv, cv, ...)
        :param name: nom du fichier de donnée
        :return: None
        """
        self.items.append(self.Conteneur_data(name))

        # on récupére le nom et le type d'expérience pour créer un nouvel item
        item = QTreeWidgetItem([name, type])

        # c'est toujours un top level item, une experience ne dépends de rien
        self.addTopLevelItem(item)

        # on place l'item comme le focus
        self.setCurrentItem(item)

    """---------------------------------------------------------------------------------"""

    def add_figure(self, figure, current_data_name):
        """
        on ajoute la figure au tree en fonction de _created_from de la figure

        :param figure: objet Figure
        :param current_data_name: nom de la data auquel appartient la figure, le premier parent
        :return: None
        """
        for i, item in enumerate(self.items):
            if item.name == current_data_name:

                # la figure ne dépends pas d'une autre, on l'ajoute juste
                if figure.created_from is None:
                    # la figure n'a pas était créée à partir d'une autre

                    # on crééer un nouvel objet Conteneur
                    new_item = self.Conteneur_figure(figure.name)

                    # on l'ajoute à l'objet Conteneur_data correspondant à current_data_name
                    item.append(new_item)

                    # on crééer un nouvel objet QTreeWidgetItem
                    item = QTreeWidgetItem([figure.name, "figure"])

                    # on ajoute l'item à la place correspondante
                    self.topLevelItem(i).addChild(item)

                    # on place le focus sur le dernier ajout
                    self.setCurrentItem(item)
                else:
                    # on créer un array qui liste les "origines" de la figure en parcourant récursivement
                    # created_from de la figure est de ses parents
                    array_created_from = []
                    self.get_array_created_from(figure, array_created_from)

                    # on créer un nouvel item
                    item = QTreeWidgetItem([figure.name, "figure"])

                    # on créer obj qui correspond à l'objet qui va parcourir l'arbre logique
                    obj = self.items[i]

                    # _item lui parcous l'arbre "physique"
                    _item = self.topLevelItem(i)
                    for i, name in enumerate(array_created_from):
                        # ou parcours l'arbre en utilisant les noms obtenus par get_array_created_from
                        obj, index = obj.get_child(name)
                        _item = _item.child(index)

                    # on est au bonne endroit de l'arbre logique et physique pour ajouter litem
                    # arbre logique
                    new_item = self.Conteneur_figure(figure.name)
                    obj.append(new_item)

                    # arbre pysique
                    _item.addChild(item)
                break

    """---------------------------------------------------------------------------------"""

    def get_array_created_from(self, figure, array_res):
        """
        créer un array contenant le nom des figure ayant servis à la création de la figure passé
        en paramétre. On parcours récursivement les parent de la figure.

        :param figure: figure sur laquel la recherche de parent est effectué
        :param array_res: array dans lequel on stock les noms
        :return: array contenant les toutes les figure .created_from de figure
                 si figure à été créée à aprtir de f2, f2 à partir de f3 et f3 à partir de f4 :
                 :return [f4.name, f3.name, f2.name]
        """

        if figure.created_from is not None:
            self.get_array_created_from(figure.created_from, array_res)
            array_res.append(figure.created_from.name)

    """---------------------------------------------------------------------------------"""

    def info(self):
        """
        affiche de maniére textuel les informations de l'arbre logique

        :return: None
        """
        for conteneur in self.items:
            conteneur.get_name(0)

    """---------------------------------------------------------------------------------"""

    class Conteneur(ABC):
        """
        class abstraite de qui vont hériter Conteneur_data et Conteneur_figure
        elle fournis les methode pour aider le parcours de l'arbre logique
        """

        def __init__(self, name):
            self.name = name

        @abstractmethod
        def get_child(self, name):
            """
            return l'index et la figure correspondant au nom donnée en
            paramètre, raise ValueError si elle n'est pas présente dans
            le conteneur

            :param name: non du chiel que l'on souhaite avoir
            :return: Figure, index

            :exception ValueError
            """
            pass

        @abstractmethod
        def get_name(self, nb_tab):
            """
            Methode utilisé pour l'affichage text de l'arbre logique, nb_tab
            est incrémenté à chaque fois que l'on passe à l'affichage d'un child

            :param nb_tab: nombre tabulation pour l'affichage
            :return: None
            """
            pass

        @abstractmethod
        def append(self, item):
            """
            en fonction de la class fille l'array du conteneur ne porte pas ne même nom,
            on utilise cette methode pour append un item au conteneur

            :param item: Conteneur_data, Conteneur_figure
            :return: None
            """
            pass

    class Conteneur_data(Conteneur):
        def __init__(self, name):
            super().__init__(name)

            # objet de la class Conteneur_figure
            self.figures_child = []

        def get_child(self, name):
            for i, figure in enumerate(self.figures_child):
                if figure.name == name:
                    return figure, i
            raise ValueError

        def get_name(self, nb_tab):
            str = ""
            for i in range(nb_tab):
                str += "\t"
            str += self.name
            print(str)
            for item in self.figures_child:
                item.get_name(nb_tab + 1)

        def append(self, item):
            self.figures_child.append(item)

    class Conteneur_figure(Conteneur):
        def __init__(self, name):
            super().__init__(name)

            # objet de la class Conteneur_figure
            self.figures_child = []

        def get_child(self, name):
            for i, figure in enumerate(self.figures_child):
                if figure.name == name:
                    return figure, i
            raise ValueError

        def get_name(self, nb_tab):
            str = ""
            for i in range(nb_tab):
                str += "\t"
            str += self.name
            print(str)
            for item in self.figures_child:
                item.get_name(nb_tab + 1)

        def append(self, item):
            self.figures_child.append(item)
